  apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/4Min4m/DemoApp
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default